{% set python_min = "3.11" %}
{% set name = "sqlcompyre" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlcompyre-{{ version }}.tar.gz
  sha256: cdca99a3ea7e5ef31b87243b0ae1334ddb31784a5577c92f6620c4d72c19d9a4

build:
  entry_points:
    - compyre = sqlcompyre.cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - click
    - pydantic >=2,<3
    - pyyaml
    - sqlalchemy >=2,<3
    - tabulate
    - tqdm

test:
  imports:
    - sqlcompyre
  commands:
    - pip check
    - compyre --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quantco/sqlcompyre
  summary: Tool for comparing and inspecting data in SQL databases.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - borchero
